<?php

namespace Prajna\Objects;

class VIF
{
	public $uuid;
	public $allowed_operations;
	public $current_operations;
	public $device;
	public $network;
	public $VM;
	public $MAC;
	public $MTU;
	public $reserved;
	public $other_config;
	public $currently_attached;
	public $status_code;
	public $status_detail;
	public $runtime_properties;
	public $qos_algorithm_type;
	public $qos_algorithm_params;
	public $qos_algorithm_algorithms;
	public $metrics;
	public $MAC_autogenerated;
	public $locking_mode;
	public $ipv4_allowed;
	public $ipv6_allowed;

	public function __construct(){}
}
